#!/usr/bin/env node
// gen-config — 配置生成管道（P0 骨架）。
// 三层单一真相源：docs/*.csv（人工母表，UTF-8 BOM）→ 本脚本 → web/src/config/*.ts（强类型运行期常量）。
//
// ★P0 阶段：只立骨架 + factors 一类样板，**不切断运行期 glob**（jjbSession 仍读 web/src/data/jjdata 副本）。
//   后续 phase：逐表实现 commanders/mutators/maps/rules/bans + 把 jjbSession/jjbDoubles 的 import 切到
//   config/*.ts，删 jjdata glob + getStrArrFromFile 的 CRLF 脆弱解析链（见 projectplan「集结杯→比赛平台」§4）。
//
// 用法：node web/scripts/gen-config.mjs   （路径自适应，从仓库根或任意 cwd 跑均可）

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join, resolve } from 'path';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..', '..');                 // web/scripts → 仓库根
const docsDir = join(repoRoot, 'docs');
const outDir = join(repoRoot, 'web', 'src', 'config');

// 去 BOM + CRLF/LF 兼容 + 引号感知分列（母表 note 列存在 "..." 包裹的含逗号字段）。
function parseLine(line) {
  const out = [];
  let cur = '', inQ = false;
  for (let i = 0; i < line.length; i++) {
    const c = line[i];
    if (inQ) {
      if (c === '"') { if (line[i + 1] === '"') { cur += '"'; i++; } else inQ = false; }
      else cur += c;
    } else if (c === '"') { inQ = true; }
    else if (c === ',') { out.push(cur); cur = ''; }
    else cur += c;
  }
  out.push(cur);
  return out;
}
function parseCsv(text) {
  const clean = text.replace(/^﻿/, '').replace(/\r\n/g, '\n').trim();
  const rows = clean.split('\n').map(parseLine);
  return { header: rows[0], rows: rows.slice(1) };
}

const q = (s) => JSON.stringify(s ?? '');

// ===== 表定义（TABLES 驱动；P0 实现 factors 一类，其余留 TODO stub 形如 factors）=====
const TABLES = {
  factors: {
    src: '因子点数配置.csv',                 // 列：因子,点数,可用于自定义,单刷ban,双打ban,备注
    out: 'factors.ts',
    build(rows) {
      const items = rows.filter((r) => r[0]).map((r) => ({
        name: r[0],
        points: Number(r[1]) || 0,
        usableInCustom: r[2] === '是',
        banSolo: r[3] === '是' || r[3] === '1',
        banDouble: r[4] === '是' || r[4] === '1',
        note: (r[5] || '').trim(),
      }));
      const body = items.map((it) =>
        `  { name: ${q(it.name)}, points: ${it.points}, usableInCustom: ${it.usableInCustom}, ` +
        `banSolo: ${it.banSolo}, banDouble: ${it.banDouble}, note: ${q(it.note)} },`
      ).join('\n');
      return `// AUTO-GENERATED by web/scripts/gen-config.mjs from docs/因子点数配置.csv —— 请勿手改，改母表后重跑脚本。
export interface FactorDef {
  /** 因子中文名 */
  name: string;
  /** 点数（难度权重） */
  points: number;
  /** 是否可用于自定义突变 */
  usableInCustom: boolean;
  /** 单刷模式是否 ban */
  banSolo: boolean;
  /** 双打模式是否 ban */
  banDouble: boolean;
  /** 备注 */
  note: string;
}

/** 因子母表（${items.length} 条）。单一真相源 = docs/因子点数配置.csv。 */
export const FACTORS: readonly FactorDef[] = [
${body}
] as const;
`;
    },
  },
  // TODO(后续 phase)：
  //   commanders ← docs（指挥官档/A·B 档/种族）
  //   mutators   ← docs/官突ABC配置_官突池.csv（落实 mutatorPool.ts 的 "AUTO-GENERATED" 真生成器）
  //   maps / rules / bans ← 对应母表
  // 形如 factors：给出 { src, out, build(rows) }，本脚本 run 时自动产出 web/src/config/<out>。
};

let n = 0;
for (const [key, t] of Object.entries(TABLES)) {
  const srcPath = join(docsDir, t.src);
  if (!existsSync(srcPath)) { console.error(`SKIP ${key}: 母表缺失 docs/${t.src}`); continue; }
  const { rows } = parseCsv(readFileSync(srcPath, 'utf8'));
  writeFileSync(join(outDir, t.out), t.build(rows));
  console.log(`OK ${key}: docs/${t.src} → web/src/config/${t.out} (${rows.filter((r) => r[0]).length} 行)`);
  n++;
}
console.log(`\ngen-config 完成：${n} 个配置表生成。`);
