// AUTO-GENERATED by web/scripts/gen-config.mjs from docs/因子点数配置.csv —— 请勿手改，改母表后重跑脚本。
export interface FactorDef {
  /** 因子中文名 */
  name: string;
  /** 点数（难度权重） */
  points: number;
  /** 是否可用于自定义突变 */
  usableInCustom: boolean;
  /** 单刷模式是否 ban */
  banSolo: boolean;
  /** 双打模式是否 ban */
  banDouble: boolean;
  /** 备注 */
  note: string;
}

/** 因子母表（71 条）。单一真相源 = docs/因子点数配置.csv。 */
export const FACTORS: readonly FactorDef[] = [
  { name: "光子过载", points: 1, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "强行征用", points: 1, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "时空力场", points: 1, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "时空立场", points: 1, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "时间扭曲", points: 1, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "生命吸取", points: 1, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "生命汲取", points: 1, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "短视症", points: 1, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "轨道轰炸", points: 1, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "闪避机动", points: 1, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "震荡攻击", points: 1, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "净化光束", points: 2, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "减伤屏障", points: 2, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "坚强意志", points: 2, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "异形寄生", points: 2, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "晶矿护盾", points: 2, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "暗无天日", points: 2, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "激光钻机", points: 2, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "焦土政策", points: 2, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "行尸走肉", points: 2, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "超远视距", points: 2, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "速度狂魔", points: 2, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "默哀", points: 2, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "鼓舞人心", points: 2, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "龙卷风", points: 2, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "龙卷风暴", points: 2, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "丧尸大战", points: 3, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "伤害散射", points: 3, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "双重压力", points: 3, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "岩浆爆发", points: 3, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "无边恐惧", points: 3, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "来去无踪", points: 3, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "核弹打击", points: 3, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "自毁程序", points: 3, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "致命勾引", points: 3, usableInCustom: true, banSolo: true, banDouble: false, note: "" },
  { name: "进攻部署", points: 3, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "飞弹大战", points: 3, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "强磁雷场", points: 4, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "暴风雪", points: 4, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "复仇战士", points: 5, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "小捞油水", points: 5, usableInCustom: true, banSolo: true, banDouble: false, note: "" },
  { name: "拿钱说话", points: 5, usableInCustom: true, banSolo: true, banDouble: true, note: "" },
  { name: "灵能爆表", points: 5, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "相互摧毁", points: 5, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "虚空重生者", points: 5, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "扫雷专家", points: 6, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "杀戮机器人", points: 6, usableInCustom: true, banSolo: true, banDouble: false, note: "" },
  { name: "力量蜕变", points: 7, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "极性不定", points: 7, usableInCustom: true, banSolo: true, banDouble: false, note: "" },
  { name: "给我死吧", points: 7, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "黑死病", points: 7, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "同化体", points: 8, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "炸弹机器人", points: 10, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "虚空裂隙", points: 10, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "风暴英雄", points: 10, usableInCustom: true, banSolo: false, banDouble: false, note: "" },
  { name: "不给糖果就捣蛋", points: 0, usableInCustom: false, banSolo: false, banDouble: false, note: "限定因子,官方不进自定义/残酷+" },
  { name: "幸运红包", points: 0, usableInCustom: false, banSolo: false, banDouble: false, note: "限定因子,官方不进自定义/残酷+" },
  { name: "惧怕黑暗", points: 0, usableInCustom: false, banSolo: false, banDouble: false, note: "限定因子,官方不进自定义/残酷+" },
  { name: "捕杀火鸡", points: 0, usableInCustom: false, banSolo: false, banDouble: false, note: "限定因子,官方不进自定义/残酷+" },
  { name: "杀生业报", points: 0, usableInCustom: false, banSolo: false, banDouble: false, note: "限定因子,官方不进自定义/残酷+" },
  { name: "混乱工作室", points: 7, usableInCustom: false, banSolo: false, banDouble: false, note: "限定因子,官方不进自定义/残酷+，非酋模式恒锁因子按 7 分(yb 2026-06-30)" },
  { name: "焰火秀", points: 0, usableInCustom: false, banSolo: false, banDouble: false, note: "限定因子,官方不进自定义/残酷+" },
  { name: "礼尚往来", points: 7, usableInCustom: false, banSolo: false, banDouble: false, note: "限定因子,官方不进自定义/残酷+，非酋模式可分配因子按 7 分(yb 2026-06-30)" },
  { name: "补给共享", points: 0, usableInCustom: false, banSolo: false, banDouble: false, note: "限定因子,官方不进自定义/残酷+" },
  { name: "迷失方向", points: 0, usableInCustom: false, banSolo: false, banDouble: false, note: "限定因子,官方不进自定义/残酷+" },
  { name: "上班偷睡", points: 0, usableInCustom: false, banSolo: false, banDouble: false, note: "仅编辑器,任何模式都没有" },
  { name: "不死邪魔", points: 0, usableInCustom: false, banSolo: false, banDouble: false, note: "仅编辑器,任何模式都没有" },
  { name: "刺头兵", points: 0, usableInCustom: false, banSolo: false, banDouble: false, note: "仅编辑器,任何模式都没有" },
  { name: "极度谨慎", points: 0, usableInCustom: false, banSolo: false, banDouble: false, note: "仅编辑器,任何模式都没有" },
  { name: "消极战斗", points: 0, usableInCustom: false, banSolo: false, banDouble: false, note: "仅编辑器,任何模式都没有" },
  { name: "石像狂热者", points: 0, usableInCustom: false, banSolo: false, banDouble: false, note: "仅编辑器,任何模式都没有" },
] as const;
